version: '3'

services:
  server:
    build: .
    image: dm3loc/mrna_backend
    stdin_open: true
    tty: true
    expose: 
      - 5000
    environment:
      API_HOST: "http://localhost:3000"
      APP_SERVER_PORT: 5000
    ports:
      - '5000:5000'
    command: sh -c "cd /mRNA && node app.js"
  web:
    build: ./web
    image: dm3loc/mrna_web
    stdin_open: true
    tty: true
    expose: 
      - 3333
    ports:
      - '3335:3335'
    links: 
      - server
    command: sh -c "export PORT=3335 && npm start"


