version: '3'

services:
  web:
    build: .
    # image: dm3loc/mrna_web
    # stdin_open: true
    container_name: "G2PDeep-Frontend"
    command: sh -c "export PORT=3335 && npm start"
    tty: true
    expose: 
      - 80
    ports:
      - '80:3335'


