version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "G2PDeep-Frontend"
    command: sh -c "export PORT=3335 && npm start"
    tty: true
    volumes:
      - .:/usr/src/app
      - '/usr/src/app/node_modules'
    expose: 
      - 80
    ports:
      - '80:3335'


